### ISSUE TITLE
Egit integration doesn't work anymore after plugin installation

### ISSUE THREAD

**Issue by mojo2012** [SAP/hybris-commerce-eclipse-plugin#24] opened 2018-01-16 12:08 UTC
After installing the plugin and reimporting all my projects, the "Team" menu didn't work anymore. I had to call "Team / share" again on each project (>30).
That never happened to be before.

**Comment by brendandobbs** [comment] 2018-01-16 15:54
I tried to reproduce this however my custom extensions are still shared (Eclipse Oxygen) after both importing and synchronizing the workspace. 

Does it happen again after you synchronize or only on import?

**Comment by mojo2012** [comment] 2018-01-17 07:27
It only happened once after the import. After reconnecting/sharing it stayed. There were no changes in git - so I guess the workspace may have been corrupted.

I use the latest eclipse oxygen. I didn't change any settings in the import wizard.

**Comment by mikolayek** [comment] 2020-01-07 13:43
I was not able to reproduce bug. Closing issue

**Closed by mikolayek** 2020-01-07 13:43 UTC
